# Generated by Django 4.0 on 2021-12-26 13:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0002_remove_moviesession_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 13, 9, 58, 884915, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 26, 13, 9, 58, 884915, tzinfo=utc)),
        ),
    ]
