# Generated by Django 4.0 on 2022-01-13 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0003_alter_moviesession_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 17, 46, 17, 582969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 13, 17, 46, 17, 582969, tzinfo=utc)),
        ),
    ]
