# Generated by Django 4.0.5 on 2022-06-19 13:31

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('kino_app', '0004_alter_moviesession_end_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cont', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=1000)),
                ('time_to_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='/static/421-4212341_default-avatar-svg-hd-png-download.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviesession',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 13, 31, 19, 24020, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 19, 13, 31, 19, 23986, tzinfo=utc)),
        ),
    ]
