# Generated by Django 4.0.5 on 2022-06-20 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0005_contacts_customer_avatar_moviesession_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='end_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
