# Generated by Django 4.0.5 on 2022-06-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0006_alter_moviesession_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
