# Generated by Django 4.0.5 on 2022-06-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0007_alter_moviesession_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesession',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AlterField(
            model_name='moviesession',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
