# Generated by Django 4.0.5 on 2022-07-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_app', '0013_alter_customer_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.ImageField(default='static/avatar.png', upload_to='avatar/'),
        ),
    ]
